### ISSUE TITLE
Replace React-Bootstrap

### ISSUE THREAD

**Issue by a11rew** [zurichat/zc_plugin_reminder#164]

**Comment by Acelewy** [comment]
https://react-bootstrap.github.io/getting-started/introduction/

This is really helpful

**Comment by a11rew** [comment]
> https://react-bootstrap.github.io/getting-started/introduction/
> 
> This is really helpful

Thanks! I'll add it in the readme under the component lib section

**Comment by a11rew** [comment]
Re-opening to replace react-bootstrap with HeadlessUI
