### ISSUE TITLE
Database endpoints

### ISSUE THREAD

**Issue by iyosayi** [zurichat/zc_plugin_reminder#174]
Create different functions that make calls to the `zc_core` DB API endpoints.

### Acceptance
- [x] #175
- [ ] I have a `updateOne` function @a11rew 
- [ ] I have a `deleteOne` function @Sodiq-123 
- [ ] I have a `findbyId` function  @Tofunmiakin 
- [ ] I have a `findAll` function @moh-x

**Comment by iyosayi** [comment]
DUPLICATE!

**Comment by xodeeq** [comment]
Testable link for the working findAll DB function: https://reminders.zuri.chat/api/v1/all-reminders
