### ISSUE TITLE
View `Set Deadline` button

### ISSUE THREAD

**Issue by Tokonigeorge** [zurichat/zc_plugin_reminder#202]
As an admin I should be able to see a set deadline button.

### Acceptance 
- [ ] I can see a set deadline button.

**Comment by iyosayi** [comment]
Where's the PR for this? If you are marking the checkbox? @Tokonigeorge

**Comment by MaryAyokanmiOre** [comment]
This issue was assigned to 2 people or more and due to conflicts, I was reassigned.
