### ISSUE TITLE
Get all reminders Route

### ISSUE THREAD

**Issue by iyosayi** [zurichat/zc_plugin_reminder#232]
As a user, I need to have different endpoints that I can access to get data provided on the frontend. All these endpoints should be inside the `/src/controllers/reminder.controller.js` file

### Acceptance
- [ ] I have a `getAll` endpoint that returns all the reminders/deadlines in the database @haastrupea

**Comment by haastrupea** [comment]
[To test]
Visit https://reminders.zuri.chat/api/v1/reminders to see all reminders from db

@iyosayi
