### ISSUE TITLE
Write to DB

### ISSUE THREAD

**Issue by iyosayi** [zurichat/zc_plugin_reminder#234]
As a user, I should be able to save my reminders in the database so I can retrieve them later on.

### Acceptance
- [ ] I have a function that calls the `zc_core` write endpoint to store information in the database

**Comment by Comurule** [comment]
Live Link: this can only be tested with Postman as we're instructed not to tamper with Frontend folder. https://reminders.zuri.chat/api/v1/reminders

Here's an online rest API tester: https://reqbin.com/
