### ISSUE TITLE
Update data function

### ISSUE THREAD

**Issue by iyosayi** [zurichat/zc_plugin_reminder#235]
As a user, I should be able to update the information I stored in the database so I can see the updated version anytime.

### Acceptance
- [ ] I have a `updateOne` function that takes an Id and the details to update and makes calls to the zc_core UPDATE endpoint.

**Comment by hadedeji10k** [comment]
@iyosayi  is this about a reminder?

update a reminder?

**Comment by Augusta-E** [comment]
yes

**Comment by hadedeji10k** [comment]
Are you done with it?
