### ISSUE TITLE
View Cards on Main Overview Board 

### ISSUE THREAD

**Issue by jutivia** [zurichat/zc_plugin_reminder#3]
As a user, I should be able to view the cards on main activity board which shows the 

- name of task
- shortened description of task
- start date and time of task
- End date and time of task
- hours till deadline of task
- first 4 pictures of assignees 

### Acceptance
- [ ] I can view cards in the main activity board. 
- [ ] Each card contains the name of tasks, shortened description of tasks, start and end date of task, hours till deadline of task and first 4 pictures of assignees.

**Comment by jutivia** [comment]
This issue cannot be done until the issue #4 is done, as the data from #4 is needed for this issue

**Comment by fidelmak** [comment]
okay
