### ISSUE TITLE
UniqueConstraintError handlers

### ISSUE THREAD

**Issue by iyosayi** [zurichat/zc_plugin_reminder#304]
As a user, I should be able to get errors when I input bad data or when I try to do an invalid operation. We have the following error classes in `/src/shared/errors/ErrorClass.js` that extend the `Error` object to handle errors:

- UniqueConstraintError - should have a `statusCode` of 409

**Comment by d0bbl** [comment]
Issue #304
I have created a unique constraint error class which extends the error class. and I provided a functionality for returning an error - 409, to end users when they make a duplicate error.
To test visit [live link](https://reminders.zuri.chat/api/v1/conflictError) 

CC: @iyosayi
