### ISSUE TITLE
[Housekeeping] Update deadline list sections to reuse display components

### ISSUE THREAD

**Issue by a11rew** [zurichat/zc_plugin_reminder#395]
Tasks
- [ ] Time, due date and start date component duplicated are removed in `/deadlineList` and `/deadlineStatus` with both sections reusing the same components

**Comment by Ekpa-N** [comment]
I'll work on this one if that's okay, since it's an extension of my previous task.

**Comment by triggac4** [comment]
i think what is best here is to send the deadline status's date component to the overall component folder then the dueDate and startDate of both deadline status and deadline list should be derived from it... so with that they are all just extensions of the overrall date component  @a11rew .. what do you think

**Comment by Ekpa-N** [comment]
We might also have to rename the date component since the data both components will be using includes task details and assignees.
So it's a larger component than just date.
