### ISSUE TITLE
Avatar stack 

### ISSUE THREAD

**Issue by a11rew** [zurichat/zc_plugin_reminder#400]
Improve and finish implementation of the avatar stack component in `frontend/src/deadlineList/components/userAvatar.jsx`

Tasks
- [x] The component takes 4 images as input and returns them stacked like in the Figma mockup (See image)
- [x] The component fills the parent container
- [ ] Individual avatars in the stack have the green outline ring like in the mockup
- [ ] On hover, the stack should expand to show avatars of individual users
- [ ] On hover, the stack should show a tooltip with the names of the assignees.

![stack](https://user-images.githubusercontent.com/87580113/132144482-ac11b2b3-cf59-4110-9e98-bd3d8aff65d2.png)

**Comment by triggac4** [comment]
This can be arranged.. will get to it
