### ISSUE TITLE
Summary Modal

### ISSUE THREAD

**Issue by a11rew** [zurichat/zc_plugin_reminder#401]
Implement the deadline summary modal that shows on first load

- [ ] Implement modal according to design mockup
- [ ] Deadline shows on first load and records closed state so it doesn't show on plugin reload for an amount of time (say 24 hours)
- [ ] Cards shown in modal are sorted based on priority

See design here

![popup](https://user-images.githubusercontent.com/87580113/132144575-12e5ad45-973b-4401-9da2-d9ab54edba85.png)

**Comment by Timonwa** [comment]
Cool. I would take the first task then, on implementation of the design.

**Comment by stephanieopala** [comment]
I'll take the second task

**Comment by stephanieopala** [comment]
@Timonwa @misspee007 Should we create a group so that we can have further discussions on this issue there, since we're all working on it?

**Comment by misspee007** [comment]
ah, it is well oh. 
@stephanieopala I don't mind.

**Comment by Timonwa** [comment]
Yes. That would be great. My WhatsApp name is timonwa in the group chat.

**Comment by misspee007** [comment]
@Timonwa It appears you have been unassigned from this issue.

**Comment by misspee007** [comment]
I'll take the third task.
