### ISSUE TITLE
Deadline Status Nav

### ISSUE THREAD

**Issue by a11rew** [zurichat/zc_plugin_reminder#410]
Task

- [ ] The nav (tabSwitcher) for the deadline status section stays visible on screen during overflow.
- [ ] The nav bar sticks to the top of the screen when scrolled past

![ezgif-6-3338f86a51f0](https://user-images.githubusercontent.com/87580113/132191081-cc8cf321-d591-40a4-a325-f6be3c5b6d1a.gif)

**Comment by Kenkeluke** [comment]
On the nav bar(taskswitch) staying put

**Comment by praise99** [comment]
on the  nav bar sticks to the top of the screen when scrolled past

**Comment by praise99** [comment]
on the  nav bar sticks to the top of the screen when scrolled past
