### ISSUE TITLE
Edit deadline from view deadline modal

### ISSUE THREAD

**Issue by a11rew** [zurichat/zc_plugin_reminder#426]
Users should be able to view deadline information and also edit particular fields to update deadline information.

Tasks
- [ ] Allow users to update title, description and time of deadlines
- [ ] Show pencil icon indicating field is editable
- [ ] Handle loading and error states
- [ ] Add toggle to complete tasks
- [ ] Updated information is submitted to the backend to update the form

**Comment by MaryAyokanmiOre** [comment]
Working on show pencil icon, indicating that field is editable.
