### ISSUE TITLE
Setup Job to send notifications at specified times

### ISSUE THREAD

**Issue by iyosayi** [zurichat/zc_plugin_reminder#44]
As a user, I should be able to get notifications periodically, so I and my teammates can know the status of reminders via mail or notifications.

### Acceptance
- [ ] I have a scheduler running that gets all reminders and sends them at the time specified.
- [ ] I have a queue to handle the messages that are being sent by the scheduler 

#### Steps
- Install agenda from here https://www.npmjs.com/package/agenda
- Create a job, that runs every minute. Inside the job,
- Retrieve all reminders by calling the respective database function, 
- Write a logic that checks if the date is an hour to expiration, then send the reminder object to a queue
- The queue picks it up and sends the respective mails to the individuals.

**Comment by tamsay** [comment]
[live link]( https://reminders.zuri.chat/api/v1/oneHourToGo)
 https://reminders.zuri.chat/api/v1/oneHourToGo
