### ISSUE TITLE
Pages and Navigation

### ISSUE THREAD

**Issue by a11rew** [zurichat/zc_plugin_reminder#450]
Set up pages for three main sections; upcoming, overdue and completed.

Tasks
- [ ] Switching pages should not cause a reload of the page. Just show the different pages
- [ ] Set up nav bar with components according to the figma design

**Comment by misspee007** [comment]
Are the components pre-existing, or are we supposed to build them?

**Comment by a11rew** [comment]
We're using the search and sort from the previous design, - idk whether the button is reusable but we'll see

**Comment by MaryAyokanmiOre** [comment]
We are to work together and make 1 pr right?

**Comment by a11rew** [comment]
Yes

**Comment by Kenkeluke** [comment]
Yes

**Comment by MaryAyokanmiOre** [comment]
✅
